### PR TITLE
Added IDReferences and Extrinsics traits where needed by DTD

### PR DESCRIPTION
**Pull request by Rike-cz**
As I wrote in issue #6, there are some missings. I tried to fill a part of blank space with this PR.

### CODE REVIEW

**Comment by Rike-cz** [comment]
I changes all `new self(...)` to `new static(...)` because with private constructors I cannot inherit and extend that classes.

**Review by ynnoig — APPROVED** [review]
@mathielen from my site ok. Can u please perform your review too?

**Comment by mathielen** [comment]
nice job @Rike-cz thank you!

**Comment by mathielen** [comment]
> I changes all `new self(...)` to `new static(...)` because with private constructors I cannot inherit and extend that classes.

https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static

**Comment by Rike-cz** [comment]
@mathielen I understand, but in Laravel world is this technique common, e.g. [Collection](https://github.com/laravel/framework/blob/92b306639eb2449b9e99a5b1da954142e24113f7/src/Illuminate/Collections/Collection.php#L40-L55).

I can change it to safer version - use this `static` call only if constructor is private. Without this I cannot extend and override class at all, because `self` reference in static constructor (create etc.) falls back to parent class.

**Comment by mathielen** [comment]
Hmm, so the reason to override the classes is that we dont provide all the properties of the CXML dtd, right?

So we could either
* implement all cxml properties from the dtds and therefore there should be no reason to override our classes anymore
* remove the static methods and just rely  on constructors and setters
* implement the changes from @Rike-cz but mark them as "okay" so phpstan would ignore it

**Comment by Rike-cz** [comment]
> Hmm, so the reason to override the classes is that we dont provide all the properties of the CXML dtd, right?

Not exactly in this case, but it's true that DTD is not fully covered. I want to extend some models with [Conditionable trait](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Conditionable/Traits/Conditionable.php) (as in Laravel) for easier chaining methods. It's not about CXML, it's only helper for me. And class inheritance is about it too - developer can extend class with something useful for his case.

Static methods/factories are good practice and removing them will break your back compatibility.

**Pull request merged**
